---
name: Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Maintenance-issue if
        if: startsWith(github.ref_name, 'maintenance')
        run: |
          echo github.ref_name
          echo "only maintenance, do not deploy"
      
      - name: Say Deploy
        if: startsWith(github.ref_name, 'maintenance') != true
        run: |
          echo github.ref_name
          echo "not maintenance, deploy"

      - name: Check out repo
        uses: actions/checkout@v2
      
      - name: Print env
        run: |
          echo "Print all environment variables"
          env
      
      - name: Validate branch name
        run: ./.github/scripts/validate-branch-name.sh
        